# --------------------------------------------------------------------------------------------------
# Configuration for codecov.io.
# https://docs.codecov.io/docs/codecov-yaml
# --------------------------------------------------------------------------------------------------

coverage:
  range: 50..90
  round: down
  precision: 1
