# --------------------------------------------------------------------------------------------------
# Azure CI pipeline.
# More info: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript
# --------------------------------------------------------------------------------------------------

pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: ci-keys

steps:
- script: ./ci/verify-tooling.sh
  displayName: 'Verify tooling'

- script: ./ci/test.sh
  displayName: 'Test'

- script: ./ci/deploy.sh "$(Build.SourceBranch)" "$(storagestaticconnection)"
  displayName: 'Deploy'

- script: ./ci/report-coverage.sh "$(typedtreeeditor-codecov)"
  displayName: 'Publish test coverage to codecov.io'
  condition: always()

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: '$(System.DefaultWorkingDirectory)/junit.xml'
  condition: always()

- task: PublishCodeCoverageResults@1
  displayName: 'Publish test coverage to azure'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
    failIfCoverageEmpty: true
  condition: always()
