# --------------------------------------------------------------------------------------------------
# Azure CI pipeline.
# More info: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript
# --------------------------------------------------------------------------------------------------

pool:
  vmImage: 'ubuntu-22.04'

variables:
- group: ci-keys

steps:
- script: ./ci/verify-tooling.sh
  displayName: 'Verify tooling'

- script: ./ci/lint.sh
  displayName: 'Lint'

- script: ./ci/test.unit.sh
  displayName: 'Unit Test'

- script: ./ci/build.sh
  displayName: 'Build'

- script: ./ci/test.integration.sh
  displayName: 'Integration Test'

- script: ./ci/deploy.sh "$(Build.SourceBranch)" "$(storagestaticconnection)"
  displayName: 'Deploy'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build'
  inputs:
    artifactName: 'build'
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
    parallel: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish screenshots'
  inputs:
    artifactName: 'screenshots'
    PathtoPublish: '$(System.DefaultWorkingDirectory)/screenshots'
    parallel: true

- script: ./ci/report-coverage.sh "$(typedtreeeditor-codecov)"
  displayName: 'Publish test coverage to codecov.io'
  condition: always()

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: '$(System.DefaultWorkingDirectory)/*.junit.xml'
  condition: always()

- task: PublishCodeCoverageResults@1
  displayName: 'Publish test coverage to azure'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
    failIfCoverageEmpty: true
  condition: always()
